[project]
name = "agent-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "google-adk>=1.16.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]
